-- 0047 PHASE 2 -- Bilingual exercise names. The 873 imported exercises had name_es = null, and
-- genuine bilingual EN/ES is Stephanie's #1 ask. Backfills Spanish via a name_en join (movement-first
-- Spanish word order, e.g. "Barbell Squat" -> "Sentadilla con Barra"). Machine-generated v1: the core
-- (movement + equipment + position) is correct for the large majority; ~249 complex names are flagged for
-- her review but every exercise now has an understandable Spanish name. Idempotent (name-keyed, re-runnable).

update public.exercises e set name_es = v.es from (values
  ('3/4 Sit-Up', 'Abdominal 3/4'),
  ('90/90 Hamstring', 'Estiramiento Isquiotibial 90/90'),
  ('Ab Crunch Machine', 'Crunch Abdominal en Máquina'),
  ('Ab Roller', 'Rueda Abdominal'),
  ('Adductor', 'Aductor'),
  ('Adductor/Groin', 'Aductor/Ingle'),
  ('Advanced Kettlebell Windmill', 'Avanzado Molino con Pesa Rusa'),
  ('Air Bike', 'Bicicleta de Aire'),
  ('All Fours Quad Stretch', 'Estiramiento de Cuádriceps en Cuatro Apoyos'),
  ('Alternate Hammer Curl', 'Curl Martillo Alterno'),
  ('Alternate Heel Touchers', 'Toques de Talón Alterno'),
  ('Alternate Incline Dumbbell Curl', 'Curl Inclinado con Mancuerna Alterno'),
  ('Alternate Leg Diagonal Bound', 'Salto Diagonal de Piernas Alterno'),
  ('Alternating Cable Shoulder Press', 'Press de Hombros en Polea Alterno'),
  ('Alternating Deltoid Raise', 'Elevación de Deltoides Alterno'),
  ('Alternating Floor Press', 'Press en el Suelo Alterno'),
  ('Alternating Hang Clean', 'Cargada Colgante Alterno'),
  ('Alternating Kettlebell Press', 'Press con Pesa Rusa Alterno'),
  ('Alternating Kettlebell Row', 'Remo con Pesa Rusa Alterno'),
  ('Alternating Renegade Row', 'Remo Renegado Alterno'),
  ('Ankle Circles', 'Círculos de Tobillo'),
  ('Ankle On The Knee', 'de Tobillo de Rodilla'),
  ('Anterior Tibialis-SMR', 'Anterior Tibial (SMR)'),
  ('Anti-Gravity Press', 'Press Antigravedad'),
  ('Arm Circles', 'Círculos de Brazo'),
  ('Arnold Dumbbell Press', 'Press Arnold con Mancuerna'),
  ('Around The Worlds', 'Vuelta al Mundo'),
  ('Atlas Stone Trainer', 'Atlas Stone Trainer'),
  ('Atlas Stones', 'Atlas Stones'),
  ('Axle Deadlift', 'Peso Muerto con Eje'),
  ('Back Flyes - With Bands', 'Aperturas Posteriores con Banda'),
  ('Backward Drag', 'Arrastre Hacia Atrás'),
  ('Backward Medicine Ball Throw', 'Lanzamiento hacia Atrás con Balón Medicinal'),
  ('Balance Board', 'Tabla de Equilibrio'),
  ('Ball Leg Curl', 'Curl Femoral con Pelota'),
  ('Band Assisted Pull-Up', 'Dominada Asistido con Banda'),
  ('Band Good Morning', 'Buenos Días con Banda'),
  ('Band Good Morning (Pull Through)', 'Buenos Días (Pull Through) con Banda'),
  ('Band Hip Adductions', 'Aducciones de Cadera con Banda'),
  ('Band Pull Apart', 'Apertura con Banda'),
  ('Band Skull Crusher', '(Rompecráneos) con Banda'),
  ('Barbell Ab Rollout', 'Rueda Abdominal Abdominal con Barra'),
  ('Barbell Ab Rollout - On Knees', 'Rueda Abdominal de Rodillas Abdominal con Barra'),
  ('Barbell Bench Press - Medium Grip', 'Press de Banca con Barra con Agarre Medio'),
  ('Barbell Curl', 'Curl con Barra'),
  ('Barbell Curls Lying Against An Incline', 'Curls contra Inclinado Acostado con Barra'),
  ('Barbell Deadlift', 'Peso Muerto con Barra'),
  ('Barbell Full Squat', 'Sentadilla Completa con Barra'),
  ('Barbell Glute Bridge', 'Puente de Glúteos con Barra'),
  ('Barbell Guillotine Bench Press', 'Press de Banca Guillotina con Barra'),
  ('Barbell Hack Squat', 'Sentadilla Hack con Barra'),
  ('Barbell Hip Thrust', 'Empuje de Cadera con Barra'),
  ('Barbell Incline Bench Press - Medium Grip', 'Press de Banca Inclinado con Barra con Agarre Medio'),
  ('Barbell Incline Shoulder Raise', 'Elevación de Hombros Inclinado con Barra'),
  ('Barbell Lunge', 'Zancada con Barra'),
  ('Barbell Rear Delt Row', 'Remo de Deltoides Posterior con Barra'),
  ('Barbell Rollout from Bench', 'Rueda Abdominal en Banco con Barra'),
  ('Barbell Seated Calf Raise', 'Elevación de Talones Sentado con Barra'),
  ('Barbell Shoulder Press', 'Press de Hombros con Barra'),
  ('Barbell Shrug', 'Encogimiento con Barra'),
  ('Barbell Shrug Behind The Back', 'Encogimiento con Barra tras la Espalda'),
  ('Barbell Side Bend', 'Flexión Lateral con Barra'),
  ('Barbell Side Split Squat', 'Sentadilla Dividida Lateral con Barra'),
  ('Barbell Squat', 'Sentadilla con Barra'),
  ('Barbell Squat To A Bench', 'Sentadilla con Barra a Banco'),
  ('Barbell Step Ups', 'de Paso con Barra'),
  ('Barbell Walking Lunge', 'Zancada Caminando con Barra'),
  ('Battling Ropes', 'Cuerdas de Batalla'),
  ('Bear Crawl Sled Drags', 'Reptación Bear Drags con Trineo'),
  ('Behind Head Chest Stretch', 'Estiramiento de Pecho tras la Cabeza'),
  ('Bench Dips', 'Fondos en Banco'),
  ('Bench Jump', 'Salto en Banco'),
  ('Bench Press - Powerlifting', 'Press de Banca (Powerlifting)'),
  ('Bench Press - With Bands', 'Press de Banca con Bandas'),
  ('Bench Press with Chains', 'Press de Banca con Cadenas'),
  ('Bench Sprint', 'en Banco Sprint'),
  ('Bent Over Barbell Row', 'Remo Inclinado con Barra'),
  ('Bent Over Dumbbell Rear Delt Raise With Head On Bench', 'Elevación de Deltoides de Cabeza Posterior Inclinado con Mancuerna en Banco'),
  ('Bent Over Low-Pulley Side Lateral', 'en Polea Baja Lateral Lateral Inclinado'),
  ('Bent Over One-Arm Long Bar Row', 'Remo Largo Barra Inclinado a Un Brazo'),
  ('Bent Over Two-Arm Long Bar Row', 'Remo a Dos Brazos Largo Barra Inclinado'),
  ('Bent Over Two-Dumbbell Row', 'Remo con Dos Mancuernas Inclinado'),
  ('Bent Over Two-Dumbbell Row With Palms In', 'Remo con Dos Mancuernas Palmas Inclinado'),
  ('Bent Press', 'Press Inclinado'),
  ('Bent-Arm Barbell Pullover', 'Pull-over con Brazos Flexionados con Barra'),
  ('Bent-Arm Dumbbell Pullover', 'Pull-over con Brazos Flexionados con Mancuerna'),
  ('Bent-Knee Hip Raise', 'Elevación con Rodillas Flexionadas de Cadera'),
  ('Bicycling', 'Ciclismo'),
  ('Bicycling, Stationary', 'Bicicleta Estática'),
  ('Board Press', 'Press con Tabla'),
  ('Body Tricep Press', 'Press Corporal de Tríceps'),
  ('Body-Up', 'Corporal hacia Arriba'),
  ('Bodyweight Flyes', 'Aperturas'),
  ('Bodyweight Mid Row', 'Remo Mid'),
  ('Bodyweight Squat', 'Sentadilla con Peso Corporal'),
  ('Bodyweight Walking Lunge', 'Zancada Caminando'),
  ('Bosu Ball Cable Crunch With Side Bends', 'Flexiones en Bosu con Pelota Crunch Lateral en Polea'),
  ('Bottoms Up', 'Boca Abajo (Bottoms Up)'),
  ('Bottoms-Up Clean From The Hang Position', 'Cargada Boca Abajo Colgante Position'),
  ('Box Jump (Multiple Response)', 'Salto al Cajón (Multiple Response)'),
  ('Box Skip', 'en Cajón Skip'),
  ('Box Squat', 'Sentadilla al Cajón'),
  ('Box Squat with Bands', 'Sentadilla en Cajón con Bandas'),
  ('Box Squat with Chains', 'Sentadilla en Cajón con Cadenas'),
  ('Brachialis-SMR', 'Brachialis (SMR)'),
  ('Bradford/Rocky Presses', 'Press Bradford/Rocky'),
  ('Butt Lift (Bridge)', 'Elevación de Glúteos (Puente)'),
  ('Butt-Ups', 'Elevaciones de Glúteos'),
  ('Butterfly', 'Butterfly'),
  ('Cable Chest Press', 'Press de Pecho en Polea'),
  ('Cable Crossover', 'Cruce en Polea'),
  ('Cable Crunch', 'Crunch en Polea'),
  ('Cable Deadlifts', 'Deadlifts en Polea'),
  ('Cable Hammer Curls - Rope Attachment', 'Curls Martillo con Cuerda con Accesorio en Polea'),
  ('Cable Hip Adduction', 'Aducción de Cadera en Polea'),
  ('Cable Incline Pushdown', 'Extensión en Polea Inclinado en Polea'),
  ('Cable Incline Triceps Extension', 'Extensión de Tríceps Inclinado en Polea'),
  ('Cable Internal Rotation', 'Rotación Interna en Polea'),
  ('Cable Iron Cross', 'Iron Cruzado en Polea'),
  ('Cable Judo Flip', 'Judo Flip en Polea'),
  ('Cable Lying Triceps Extension', 'Extensión de Tríceps Acostado en Polea'),
  ('Cable One Arm Tricep Extension', 'Extensión de Tríceps en Polea a Un Brazo'),
  ('Cable Preacher Curl', 'Curl en Banco Scott en Polea'),
  ('Cable Rear Delt Fly', 'Apertura de Deltoides Posterior en Polea'),
  ('Cable Reverse Crunch', 'Crunch Inverso en Polea'),
  ('Cable Rope Overhead Triceps Extension', 'Extensión de Tríceps con Cuerda sobre la Cabeza en Polea'),
  ('Cable Rope Rear-Delt Rows', 'Remos con Cuerda Rear de Deltoides en Polea'),
  ('Cable Russian Twists', 'Giros Russian en Polea'),
  ('Cable Seated Crunch', 'Crunch Sentado en Polea'),
  ('Cable Seated Lateral Raise', 'Elevación Lateral Sentado en Polea'),
  ('Cable Shoulder Press', 'Press de Hombros en Polea'),
  ('Cable Shrugs', 'Encogimientos en Polea'),
  ('Cable Wrist Curl', 'Curl de Muñeca en Polea'),
  ('Calf Press', 'Prensa de Pantorrillas'),
  ('Calf Press On The Leg Press Machine', 'Prensa de Piernas Press de Pantorrillas en Máquina'),
  ('Calf Raise On A Dumbbell', 'Elevación de Talones con Mancuerna'),
  ('Calf Raises - With Bands', 'Elevaciones de Pantorrillas con Bandas'),
  ('Calf Stretch Elbows Against Wall', 'Estiramiento Elbows contra en Pared de Pantorrillas'),
  ('Calf Stretch Hands Against Wall', 'Estiramiento Hands contra en Pared de Pantorrillas'),
  ('Calf-Machine Shoulder Shrug', 'Encogimiento de Pantorrilla Machine de Hombros'),
  ('Calves-SMR', 'Calves (SMR)'),
  ('Car Deadlift', 'Peso Muerto Car'),
  ('Car Drivers', 'Car Drivers'),
  ('Carioca Quick Step', 'Carioca Quick de Paso'),
  ('Cat Stretch', 'Estiramiento del Gato'),
  ('Catch and Overhead Throw', 'Lanzamiento Catch sobre la Cabeza'),
  ('Chain Handle Extension', 'Extensión Chain Handle'),
  ('Chain Press', 'Press Chain'),
  ('Chair Leg Extended Stretch', 'Estiramiento en Silla Extended de Piernas'),
  ('Chair Lower Back Stretch', 'Estiramiento en Silla Inferior de Espalda'),
  ('Chair Squat', 'Sentadilla en Silla'),
  ('Chair Upper Body Stretch', 'Estiramiento en Silla Superior Corporal'),
  ('Chest And Front Of Shoulder Stretch', 'Estiramiento de Pecho Frontal de Hombros'),
  ('Chest Push (multiple response)', 'de Empuje (Multiple Response) de Pecho'),
  ('Chest Push (single response)', 'de Empuje (Single Response) de Pecho'),
  ('Chest Push from 3 point stance', 'de Empuje 3 Point de Postura de Pecho'),
  ('Chest Push with Run Release', 'de Empuje Run Release de Pecho'),
  ('Chest Stretch on Stability Ball', 'Estiramiento de Pecho en Pelota'),
  ('Child''s Pose', 'Child''S Pose'),
  ('Chin To Chest Stretch', 'Estiramiento al Mentón al Pecho'),
  ('Chin-Up', 'Dominada Supina'),
  ('Circus Bell', 'Circus Bell'),
  ('Clean', 'Cargada'),
  ('Clean and Jerk', 'Cargada y Envión'),
  ('Clean and Press', 'Cargada y Press'),
  ('Clean Deadlift', 'Peso Muerto Clean'),
  ('Clean from Blocks', 'Cargada con Bloques'),
  ('Clean Pull', 'Tirón Clean'),
  ('Clean Shrug', 'Encogimiento Clean'),
  ('Clock Push-Up', 'Flexión Clock'),
  ('Close-Grip Barbell Bench Press', 'Press de Banca con Agarre Cerrado con Barra'),
  ('Close-Grip Dumbbell Press', 'Press con Agarre Cerrado con Mancuerna'),
  ('Close-Grip EZ Bar Curl', 'Curl con Agarre Cerrado con Barra Z'),
  ('Close-Grip EZ-Bar Curl with Band', 'Curl con Agarre Cerrado con Barra Z con Banda'),
  ('Close-Grip EZ-Bar Press', 'Press con Agarre Cerrado con Barra Z'),
  ('Close-Grip Front Lat Pulldown', 'Jalón al Pecho con Agarre Cerrado Frontal'),
  ('Close-Grip Push-Up off of a Dumbbell', 'Flexión con Agarre Cerrado con Mancuerna'),
  ('Close-Grip Standing Barbell Curl', 'Curl con Agarre Cerrado de Pie con Barra'),
  ('Cocoons', 'Capullos (Cocoons)'),
  ('Conan''s Wheel', 'Conan''S Wheel'),
  ('Concentration Curls', 'Curls Concentrado'),
  ('Cross Body Hammer Curl', 'Curl Martillo Cruzado Corporal'),
  ('Cross Over - With Bands', 'Cruzado sobre con Bandas'),
  ('Cross-Body Crunch', 'Crunch Cruzado'),
  ('Crossover Reverse Lunge', 'Zancada Inverso Cruce'),
  ('Crucifix', 'Crucifix'),
  ('Crunch - Hands Overhead', 'Crunch Hands sobre la Cabeza'),
  ('Crunch - Legs On Exercise Ball', 'Crunch de Piernas con Pelota'),
  ('Crunches', 'Abdominales'),
  ('Cuban Press', 'Press Cuban'),
  ('Dancer''s Stretch', 'Estiramiento del Bailarín'),
  ('Dead Bug', 'Bicho Muerto (Dead Bug)'),
  ('Deadlift with Bands', 'Peso Muerto con Bandas'),
  ('Deadlift with Chains', 'Peso Muerto con Cadenas'),
  ('Decline Barbell Bench Press', 'Press de Banca Declinado con Barra'),
  ('Decline Close-Grip Bench To Skull Crusher', 'en Banco con Agarre Cerrado (Rompecráneos) Declinado'),
  ('Decline Crunch', 'Crunch Declinado'),
  ('Decline Dumbbell Bench Press', 'Press de Banca Declinado con Mancuerna'),
  ('Decline Dumbbell Flyes', 'Aperturas Declinado con Mancuerna'),
  ('Decline Dumbbell Triceps Extension', 'Extensión de Tríceps Declinado con Mancuerna'),
  ('Decline EZ Bar Triceps Extension', 'Extensión de Tríceps Declinado con Barra Z'),
  ('Decline Oblique Crunch', 'Crunch Oblicuo Declinado'),
  ('Decline Push-Up', 'Flexión Declinado'),
  ('Decline Reverse Crunch', 'Crunch Inverso Declinado'),
  ('Decline Smith Press', 'Press en Máquina Smith Declinado'),
  ('Deficit Deadlift', 'Peso Muerto Deficit'),
  ('Depth Jump Leap', 'Salto en Profundidad Leap'),
  ('Dip Machine', 'Fondo en Máquina'),
  ('Dips - Chest Version', 'Fondos Version de Pecho'),
  ('Dips - Triceps Version', 'Fondos Version de Tríceps'),
  ('Donkey Calf Raises', 'Elevación de Talones Burro'),
  ('Double Kettlebell Alternating Hang Clean', 'Cargada a Dos Colgante con Pesa Rusa Alterno'),
  ('Double Kettlebell Jerk', 'Envión a Dos con Pesa Rusa'),
  ('Double Kettlebell Push Press', 'Press a Dos de Empuje con Pesa Rusa'),
  ('Double Kettlebell Snatch', 'Arranque a Dos con Pesa Rusa'),
  ('Double Kettlebell Windmill', 'a Dos Molino con Pesa Rusa'),
  ('Double Leg Butt Kick', 'a Dos Butt Patada de Piernas'),
  ('Downward Facing Balance', 'Equilibrio Boca Abajo'),
  ('Drag Curl', 'Curl Arrastre'),
  ('Drop Push', 'Drop de Empuje'),
  ('Dumbbell Alternate Bicep Curl', 'Curl de Bíceps con Mancuerna Alterno'),
  ('Dumbbell Bench Press', 'Press de Banca con Mancuerna'),
  ('Dumbbell Bench Press with Neutral Grip', 'Press de Banca con Mancuerna con Agarre Neutro'),
  ('Dumbbell Bicep Curl', 'Curl de Bíceps con Mancuerna'),
  ('Dumbbell Clean', 'Cargada con Mancuerna'),
  ('Dumbbell Floor Press', 'Press en el Suelo con Mancuerna'),
  ('Dumbbell Flyes', 'Aperturas con Mancuerna'),
  ('Dumbbell Incline Row', 'Remo Inclinado con Mancuerna'),
  ('Dumbbell Incline Shoulder Raise', 'Elevación de Hombros Inclinado con Mancuerna'),
  ('Dumbbell Lunges', 'Zancadas con Mancuerna'),
  ('Dumbbell Lying One-Arm Rear Lateral Raise', 'Elevación Lateral Posterior Acostado con Mancuerna a Un Brazo'),
  ('Dumbbell Lying Pronation', 'Pronation Acostado con Mancuerna'),
  ('Dumbbell Lying Rear Lateral Raise', 'Elevación Lateral Posterior Acostado con Mancuerna'),
  ('Dumbbell Lying Supination', 'Supination Acostado con Mancuerna'),
  ('Dumbbell One-Arm Shoulder Press', 'Press de Hombros con Mancuerna a Un Brazo'),
  ('Dumbbell One-Arm Triceps Extension', 'Extensión de Tríceps con Mancuerna a Un Brazo'),
  ('Dumbbell One-Arm Upright Row', 'Remo al Mentón con Mancuerna a Un Brazo'),
  ('Dumbbell Prone Incline Curl', 'Curl Inclinado Boca Abajo con Mancuerna'),
  ('Dumbbell Raise', 'Elevación con Mancuerna'),
  ('Dumbbell Rear Lunge', 'Zancada Posterior con Mancuerna'),
  ('Dumbbell Scaption', 'Scaption con Mancuerna'),
  ('Dumbbell Seated Box Jump', 'Salto al Cajón Sentado con Mancuerna'),
  ('Dumbbell Seated One-Leg Calf Raise', 'Elevación de Talones Sentado con Mancuerna a Una Pierna'),
  ('Dumbbell Shoulder Press', 'Press de Hombros con Mancuerna'),
  ('Dumbbell Shrug', 'Encogimiento con Mancuerna'),
  ('Dumbbell Side Bend', 'Flexión Lateral con Mancuerna'),
  ('Dumbbell Squat', 'Sentadilla con Mancuerna'),
  ('Dumbbell Squat To A Bench', 'Sentadilla con Mancuerna a Banco'),
  ('Dumbbell Step Ups', 'de Paso con Mancuerna'),
  ('Dumbbell Tricep Extension -Pronated Grip', 'Extensión de Tríceps Pronated con Agarre con Mancuerna'),
  ('Dynamic Back Stretch', 'Estiramiento Dinámico de Espalda'),
  ('Dynamic Chest Stretch', 'Estiramiento Dinámico de Pecho'),
  ('Elbow Circles', 'Círculos de Codo'),
  ('Elbow to Knee', 'de Codo de Rodilla'),
  ('Elbows Back', 'Elbows de Espalda'),
  ('Elevated Back Lunge', 'Zancada Elevado de Espalda'),
  ('Elevated Cable Rows', 'Remos Elevado en Polea'),
  ('Elliptical Trainer', 'Elíptica'),
  ('Exercise Ball Crunch', 'Crunch con Pelota'),
  ('Exercise Ball Pull-In', 'Pull con Pelota'),
  ('Extended Range One-Arm Kettlebell Floor Press', 'Press Extended Range en el Suelo con Pesa Rusa a Un Brazo'),
  ('External Rotation', 'Rotación Externa'),
  ('External Rotation with Band', 'Rotación Externa con Banda'),
  ('External Rotation with Cable', 'Rotación Externa en Polea'),
  ('EZ-Bar Curl', 'Curl con Barra Z'),
  ('EZ-Bar Skullcrusher', 'Skullcrusher con Barra Z'),
  ('Face Pull', 'Jalón a la Cara'),
  ('Farmer''s Walk', 'Caminata del Granjero'),
  ('Fast Skipping', 'Fast Skipping'),
  ('Finger Curls', 'Curls Finger'),
  ('Flat Bench Cable Flyes', 'Aperturas en Banco Plano en Polea'),
  ('Flat Bench Leg Pull-In', 'en Banco Pull de Piernas Plano'),
  ('Flat Bench Lying Leg Raise', 'Elevación de Piernas Acostado en Banco Plano'),
  ('Flexor Incline Dumbbell Curls', 'Curls Flexor Inclinado con Mancuerna'),
  ('Floor Glute-Ham Raise', 'Elevación de Glúteo Femoral en el Suelo'),
  ('Floor Press', 'Press en el Suelo'),
  ('Floor Press with Chains', 'Press en el Suelo con Cadenas'),
  ('Flutter Kicks', 'Patadas Flutter'),
  ('Foot-SMR', 'Foot (SMR)'),
  ('Forward Drag with Press', 'Press hacia Adelante Arrastre'),
  ('Frankenstein Squat', 'Sentadilla Frankenstein'),
  ('Freehand Jump Squat', 'Sentadilla con Salto Freehand'),
  ('Frog Hops', 'Saltos Rana'),
  ('Frog Sit-Ups', 'Abdominales Rana'),
  ('Front Barbell Squat', 'Sentadilla Frontal con Barra'),
  ('Front Barbell Squat To A Bench', 'Sentadilla Frontal con Barra a Banco'),
  ('Front Box Jump', 'Salto al Cajón Frontal'),
  ('Front Cable Raise', 'Elevación Frontal en Polea'),
  ('Front Cone Hops (or hurdle hops)', 'Saltos Cone Hops (Or Hurdle Frontal'),
  ('Front Dumbbell Raise', 'Elevación Frontal con Mancuerna'),
  ('Front Incline Dumbbell Raise', 'Elevación Frontal Inclinado con Mancuerna'),
  ('Front Leg Raises', 'Elevaciones Frontal de Piernas'),
  ('Front Plate Raise', 'Elevación Frontal con Disco'),
  ('Front Raise And Pullover', 'Elevación Frontal Pullover'),
  ('Front Squat (Clean Grip)', 'Cargada Squat Grip) Frontal'),
  ('Front Squats With Two Kettlebells', 'Sentadillas con Dos Kettlebells Frontal'),
  ('Front Two-Dumbbell Raise', 'Elevación con Dos Mancuernas Frontal'),
  ('Full Range-Of-Motion Lat Pulldown', 'Jalón al Pecho Completa Range Motion'),
  ('Gironda Sternum Chins', 'Dominadas al Esternón (Gironda)'),
  ('Glute Ham Raise', 'Elevación Femoral de Glúteos'),
  ('Glute Kickback', 'Patada de Glúteo'),
  ('Goblet Squat', 'Sentadilla Goblet'),
  ('Good Morning', 'Buenos Días'),
  ('Good Morning off Pins', 'Buenos Días Pins'),
  ('Gorilla Chin/Crunch', 'Gorilla Chin/Crunch'),
  ('Groin and Back Stretch', 'Estiramiento de Ingle de Espalda'),
  ('Groiners', 'Groiners'),
  ('Hack Squat', 'Sentadilla Hack'),
  ('Hammer Curls', 'Curls Martillo'),
  ('Hammer Grip Incline DB Bench Press', 'Press de Banca Martillo con Agarre Db Inclinado'),
  ('Hamstring Stretch', 'Estiramiento Isquiotibial'),
  ('Hamstring-SMR', 'Hamstring (SMR)'),
  ('Handstand Push-Ups', 'Flexiones en Pino'),
  ('Hang Clean', 'Cargada Colgante'),
  ('Hang Clean - Below the Knees', 'Cargada Colgante Below de Rodillas'),
  ('Hang Snatch', 'Arranque Colgante'),
  ('Hang Snatch - Below Knees', 'Arranque Colgante Below de Rodillas'),
  ('Hanging Bar Good Morning', 'Buenos Días Barra Colgado'),
  ('Hanging Leg Raise', 'Elevación de Piernas Colgado'),
  ('Hanging Pike', 'en V (Pike) Colgado'),
  ('Heaving Snatch Balance', 'Arranque Heaving Balance'),
  ('Heavy Bag Thrust', 'Empuje Heavy Bag'),
  ('High Cable Curls', 'Curls Alto en Polea'),
  ('Hip Circles (prone)', 'Círculos de Cadera (boca abajo)'),
  ('Hip Extension with Bands', 'Extensión de Cadera con Banda'),
  ('Hip Flexion with Band', 'de Cadera Flexion con Banda'),
  ('Hip Lift with Band', 'de Cadera Levantamiento con Banda'),
  ('Hug A Ball', 'Hug con Pelota'),
  ('Hug Knees To Chest', 'Hug de Rodillas al Pecho'),
  ('Hurdle Hops', 'Saltos Hurdle'),
  ('Hyperextensions (Back Extensions)', 'Extensiones Hiperextensiones (Back'),
  ('Hyperextensions With No Hyperextension Bench', 'Hiperextensiones No Hiperextensión en Banco'),
  ('Iliotibial Tract-SMR', 'Iliotibial Tract (SMR)'),
  ('Inchworm', 'Gusano (Inchworm)'),
  ('Incline Barbell Triceps Extension', 'Extensión de Tríceps Inclinado con Barra'),
  ('Incline Bench Pull', 'Tirón en Banco Inclinado'),
  ('Incline Cable Chest Press', 'Press de Pecho Inclinado en Polea'),
  ('Incline Cable Flye', 'Apertura Inclinado en Polea'),
  ('Incline Dumbbell Bench With Palms Facing In', 'en Banco Palmas Facing Inclinado con Mancuerna'),
  ('Incline Dumbbell Curl', 'Curl Inclinado con Mancuerna'),
  ('Incline Dumbbell Flyes', 'Aperturas Inclinado con Mancuerna'),
  ('Incline Dumbbell Flyes - With A Twist', 'Giro Flyes Inclinado con Mancuerna'),
  ('Incline Dumbbell Press', 'Press Inclinado con Mancuerna'),
  ('Incline Hammer Curls', 'Curls Martillo Inclinado'),
  ('Incline Inner Biceps Curl', 'Curl de Bíceps Inner Inclinado'),
  ('Incline Push-Up', 'Flexión Inclinado'),
  ('Incline Push-Up Close-Grip', 'Flexión con Agarre Cerrado Inclinado'),
  ('Incline Push-Up Depth Jump', 'Flexión con Salto en Profundidad Inclinado'),
  ('Incline Push-Up Medium', 'Flexión Medio Inclinado'),
  ('Incline Push-Up Reverse Grip', 'Flexión Inclinado con Agarre Inverso'),
  ('Incline Push-Up Wide', 'Flexión Abierto Inclinado'),
  ('Intermediate Groin Stretch', 'Estiramiento Intermediate de Ingle'),
  ('Intermediate Hip Flexor and Quad Stretch', 'Estiramiento Intermediate de Cadera Flexor de Cuádriceps'),
  ('Internal Rotation with Band', 'Rotación Interna con Banda'),
  ('Inverted Row', 'Remo Invertido'),
  ('Inverted Row with Straps', 'Remo Invertido Straps'),
  ('Iron Cross', 'Cruz de Hierro'),
  ('Iron Crosses (stretch)', 'Estiramiento Iron Crosses'),
  ('Isometric Chest Squeezes', 'Squeezes Isométrico de Pecho'),
  ('Isometric Neck Exercise - Front And Back', 'de Espalda Isométrico Frontal de Cuello'),
  ('Isometric Neck Exercise - Sides', 'a los Lados Isométrico de Cuello'),
  ('Isometric Wipers', 'Wipers Isométrico'),
  ('IT Band and Glute Stretch', 'Estiramiento It de Glúteos con Banda'),
  ('Jackknife Sit-Up', 'Abdominal Navaja'),
  ('Janda Sit-Up', 'Abdominal Janda'),
  ('Jefferson Squats', 'Sentadillas Jefferson'),
  ('Jerk Balance', 'Envión Balance'),
  ('Jerk Dip Squat', 'Sentadilla Jerk Dip'),
  ('JM Press', 'Press Jm'),
  ('Jogging, Treadmill', 'Trote en Cinta'),
  ('Keg Load', 'Keg Load'),
  ('Kettlebell Arnold Press', 'Press Arnold con Pesa Rusa'),
  ('Kettlebell Dead Clean', 'Cargada Dead con Pesa Rusa'),
  ('Kettlebell Figure 8', 'Figure 8 con Pesa Rusa'),
  ('Kettlebell Hang Clean', 'Cargada Colgante con Pesa Rusa'),
  ('Kettlebell One-Legged Deadlift', 'Peso Muerto a Una de Piernas con Pesa Rusa'),
  ('Kettlebell Pass Between The Legs', 'Pass Between de Piernas con Pesa Rusa'),
  ('Kettlebell Pirate Ships', 'Pirate Ships con Pesa Rusa'),
  ('Kettlebell Pistol Squat', 'Sentadilla Pistol con Pesa Rusa'),
  ('Kettlebell Seated Press', 'Press Sentado con Pesa Rusa'),
  ('Kettlebell Seesaw Press', 'Press Seesaw con Pesa Rusa'),
  ('Kettlebell Sumo High Pull', 'Tirón Alto Sumo con Pesa Rusa'),
  ('Kettlebell Thruster', 'Thruster con Pesa Rusa'),
  ('Kettlebell Turkish Get-Up (Lunge style)', 'Zancada Turkish hacia Arriba Style) con Pesa Rusa'),
  ('Kettlebell Turkish Get-Up (Squat style)', 'Sentadilla Turkish hacia Arriba Style) con Pesa Rusa'),
  ('Kettlebell Windmill', 'Molino con Pesa Rusa'),
  ('Kipping Muscle Up', 'Kipping Muscle hacia Arriba'),
  ('Knee Across The Body', 'de Rodilla Across Corporal'),
  ('Knee Circles', 'Círculos de Rodilla'),
  ('Knee Tuck Jump', 'Salto con Rodillas al Pecho'),
  ('Knee/Hip Raise On Parallel Bars', 'Elevación Knee/Hip Parallel Bars'),
  ('Kneeling Arm Drill', 'de Brazo Drill de Rodillas'),
  ('Kneeling Cable Crunch With Alternating Oblique Twists', 'Giros Crunch Oblicuo de Rodillas en Polea Alterno'),
  ('Kneeling Cable Triceps Extension', 'Extensión de Tríceps de Rodillas en Polea'),
  ('Kneeling Forearm Stretch', 'Estiramiento de Antebrazo de Rodillas'),
  ('Kneeling High Pulley Row', 'Remo en Polea Alto de Rodillas'),
  ('Kneeling Hip Flexor', 'de Cadera Flexor de Rodillas'),
  ('Kneeling Jump Squat', 'Sentadilla con Salto de Rodillas'),
  ('Kneeling Single-Arm High Pulley Row', 'Remo en Polea Alto de Rodillas a Un Brazo'),
  ('Kneeling Squat', 'Sentadilla de Rodillas'),
  ('Landmine 180''s', 'Landmine 180''S'),
  ('Landmine Linear Jammer', 'Landmine Lineal Jammer'),
  ('Lateral Bound', 'Salto Lateral'),
  ('Lateral Box Jump', 'Salto al Cajón Lateral'),
  ('Lateral Cone Hops', 'Saltos Cone Lateral'),
  ('Lateral Raise - With Bands', 'Elevación Lateral con Bandas'),
  ('Latissimus Dorsi-SMR', 'Latissimus Dorsi (SMR)'),
  ('Leg Extensions', 'Extensiones de Cuádriceps'),
  ('Leg Lift', 'Levantamiento de Piernas'),
  ('Leg Press', 'Prensa de Piernas'),
  ('Leg Pull-In', 'Encogimiento de Piernas'),
  ('Leg-Over Floor Press', 'Press Leg sobre en el Suelo'),
  ('Leg-Up Hamstring Stretch', 'Estiramiento Leg hacia Arriba Femoral'),
  ('Leverage Chest Press', 'Press de Pecho en Máquina'),
  ('Leverage Deadlift', 'Peso Muerto en Máquina'),
  ('Leverage Decline Chest Press', 'Press de Pecho en Máquina Declinado'),
  ('Leverage High Row', 'Remo en Máquina Alto'),
  ('Leverage Incline Chest Press', 'Press de Pecho en Máquina Inclinado'),
  ('Leverage Iso Row', 'Remo en Máquina Iso'),
  ('Leverage Shoulder Press', 'Press de Hombros en Máquina'),
  ('Leverage Shrug', 'Encogimiento en Máquina'),
  ('Linear 3-Part Start Technique', 'Técnica de Salida Lineal en 3 Partes'),
  ('Linear Acceleration Wall Drill', 'Lineal Acceleration en Pared Drill'),
  ('Linear Depth Jump', 'Salto Lineal en Profundidad'),
  ('Log Lift', 'Log Levantamiento'),
  ('London Bridges', 'London Bridges'),
  ('Looking At Ceiling', 'Looking At Ceiling'),
  ('Low Cable Crossover', 'Cruce Bajo en Polea'),
  ('Low Cable Triceps Extension', 'Extensión de Tríceps Bajo en Polea'),
  ('Low Pulley Row To Neck', 'Remo en Polea Bajo al Cuello'),
  ('Lower Back Curl', 'Curl Inferior de Espalda'),
  ('Lower Back-SMR', 'Inferior de Espalda (SMR)'),
  ('Lunge Pass Through', 'Zancada Pass Through'),
  ('Lunge Sprint', 'Sprint con Zancadas'),
  ('Lying Bent Leg Groin', 'Inclinado de Ingle de Piernas Acostado'),
  ('Lying Cable Curl', 'Curl Acostado en Polea'),
  ('Lying Cambered Barbell Row', 'Remo Cambered Acostado con Barra'),
  ('Lying Close-Grip Bar Curl On High Pulley', 'Curl con Agarre Cerrado Barra en Polea Alto Acostado'),
  ('Lying Close-Grip Barbell Triceps Extension Behind The Head', 'Extensión de Tríceps con Agarre Cerrado Behind de Cabeza Acostado con Barra'),
  ('Lying Close-Grip Barbell Triceps Press To Chin', 'Press con Agarre Cerrado al Mentón de Tríceps Acostado con Barra'),
  ('Lying Crossover', 'Cruce Acostado'),
  ('Lying Dumbbell Tricep Extension', 'Extensión de Tríceps Acostado con Mancuerna'),
  ('Lying Face Down Plate Neck Resistance', 'Face hacia Abajo Resistance de Cuello Acostado con Disco'),
  ('Lying Face Up Plate Neck Resistance', 'Face hacia Arriba Resistance de Cuello Acostado con Disco'),
  ('Lying Glute', 'Estiramiento de Glúteos Acostado'),
  ('Lying Hamstring', 'Estiramiento Isquiotibial Acostado'),
  ('Lying High Bench Barbell Curl', 'Curl en Banco Alto Acostado con Barra'),
  ('Lying Leg Curls', 'Curls de Piernas Acostado'),
  ('Lying Machine Squat', 'Sentadilla Acostado en Máquina'),
  ('Lying One-Arm Lateral Raise', 'Elevación Lateral Acostado a Un Brazo'),
  ('Lying Prone Quadriceps', 'Cuádriceps Boca Abajo'),
  ('Lying Rear Delt Raise', 'Elevación de Deltoides Posterior Acostado'),
  ('Lying Supine Dumbbell Curl', 'Curl Acostado Boca Arriba con Mancuerna'),
  ('Lying T-Bar Row', 'Remo T Barra Acostado'),
  ('Lying Triceps Press', 'Press de Tríceps Acostado'),
  ('Machine Bench Press', 'Press de Banca en Máquina'),
  ('Machine Bicep Curl', 'Curl de Bíceps en Máquina'),
  ('Machine Preacher Curls', 'Curls en Banco Scott en Máquina'),
  ('Machine Shoulder (Military) Press', 'Press (Military) de Hombros en Máquina'),
  ('Machine Triceps Extension', 'Extensión de Tríceps en Máquina'),
  ('Medicine Ball Chest Pass', 'Pass de Pecho con Balón Medicinal'),
  ('Medicine Ball Full Twist', 'Giro Completa con Balón Medicinal'),
  ('Medicine Ball Scoop Throw', 'Lanzamiento Scoop con Balón Medicinal'),
  ('Middle Back Shrug', 'Encogimiento Middle de Espalda'),
  ('Middle Back Stretch', 'Estiramiento Middle de Espalda'),
  ('Mixed Grip Chin', 'Mixed con Agarre al Mentón'),
  ('Monster Walk', 'Caminata Monster'),
  ('Mountain Climbers', 'Mountain Climbers'),
  ('Moving Claw Series', 'Moving Claw Series'),
  ('Muscle Snatch', 'Arranque Muscle'),
  ('Muscle Up', 'Muscle-Up'),
  ('Narrow Stance Hack Squats', 'Sentadillas Cerrado de Postura Hack'),
  ('Narrow Stance Leg Press', 'Prensa de Piernas Cerrado de Postura'),
  ('Narrow Stance Squats', 'Sentadillas Cerrado de Postura'),
  ('Natural Glute Ham Raise', 'Elevación Natural Femoral de Glúteos'),
  ('Neck Press', 'Press al Cuello'),
  ('Neck-SMR', 'de Cuello (SMR)'),
  ('Oblique Crunches', 'Crunches Oblicuo'),
  ('Oblique Crunches - On The Floor', 'Crunches Oblicuo en el Suelo'),
  ('Olympic Squat', 'Sentadilla Olympic'),
  ('On Your Side Quad Stretch', 'Estiramiento Lateral de Cuádriceps'),
  ('On-Your-Back Quad Stretch', 'Estiramiento de Espalda de Cuádriceps'),
  ('One Arm Against Wall', 'contra en Pared a Un Brazo'),
  ('One Arm Chin-Up', 'Dominada Supina a Un Brazo'),
  ('One Arm Dumbbell Bench Press', 'Press de Banca con Mancuerna a Un Brazo'),
  ('One Arm Dumbbell Preacher Curl', 'Curl en Banco Scott con Mancuerna a Un Brazo'),
  ('One Arm Floor Press', 'Press en el Suelo a Un Brazo'),
  ('One Arm Lat Pulldown', 'Jalón al Pecho a Un Brazo'),
  ('One Arm Pronated Dumbbell Triceps Extension', 'Extensión de Tríceps Pronated con Mancuerna a Un Brazo'),
  ('One Arm Supinated Dumbbell Triceps Extension', 'Extensión de Tríceps Supinated con Mancuerna a Un Brazo'),
  ('One Half Locust', 'a Una a Media Altura Locust'),
  ('One Handed Hang', 'a Una Handed Colgante'),
  ('One Knee To Chest', 'a Una de Rodilla al Pecho'),
  ('One Leg Barbell Squat', 'Sentadilla a Una de Piernas con Barra'),
  ('One-Arm Dumbbell Row', 'Remo con Mancuerna a Un Brazo'),
  ('One-Arm Flat Bench Dumbbell Flye', 'Apertura en Banco Plano con Mancuerna a Un Brazo'),
  ('One-Arm High-Pulley Cable Side Bends', 'Flexiones en Polea Alta Lateral en Polea a Un Brazo'),
  ('One-Arm Incline Lateral Raise', 'Elevación Lateral Inclinado a Un Brazo'),
  ('One-Arm Kettlebell Clean', 'Cargada con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Clean and Jerk', 'Envión Clean con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Floor Press', 'Press en el Suelo con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Jerk', 'Envión con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Military Press To The Side', 'Press Militar Lateral con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Para Press', 'Press Para con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Push Press', 'Press de Empuje con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Row', 'Remo con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Snatch', 'Arranque con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Split Jerk', 'Envión Dividida con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Split Snatch', 'Arranque Dividida con Pesa Rusa a Un Brazo'),
  ('One-Arm Kettlebell Swings', 'Balanceos con Pesa Rusa a Un Brazo'),
  ('One-Arm Long Bar Row', 'Remo Largo Barra a Un Brazo'),
  ('One-Arm Medicine Ball Slam', 'Golpe con Balón Medicinal a Un Brazo'),
  ('One-Arm Open Palm Kettlebell Clean', 'Cargada Open Palma con Pesa Rusa a Un Brazo'),
  ('One-Arm Overhead Kettlebell Squats', 'Sentadillas sobre la Cabeza con Pesa Rusa a Un Brazo'),
  ('One-Arm Side Deadlift', 'Peso Muerto Lateral a Un Brazo'),
  ('One-Arm Side Laterals', 'Laterals Lateral a Un Brazo'),
  ('One-Legged Cable Kickback', 'Patada a Una de Piernas en Polea'),
  ('Open Palm Kettlebell Clean', 'Cargada Open Palma con Pesa Rusa'),
  ('Otis-Up', 'Otis hacia Arriba'),
  ('Overhead Cable Curl', 'Curl sobre la Cabeza en Polea'),
  ('Overhead Lat', 'Dorsal sobre la Cabeza'),
  ('Overhead Slam', 'Golpe sobre la Cabeza'),
  ('Overhead Squat', 'Sentadilla sobre la Cabeza'),
  ('Overhead Stretch', 'Estiramiento sobre la Cabeza'),
  ('Overhead Triceps', 'Estiramiento de Tríceps sobre la Cabeza'),
  ('Pallof Press', 'Press Pallof'),
  ('Pallof Press With Rotation', 'Rotación Pallof Press'),
  ('Palms-Down Dumbbell Wrist Curl Over A Bench', 'Curl de Muñeca Palmas hacia Abajo sobre en Banco con Mancuerna'),
  ('Palms-Down Wrist Curl Over A Bench', 'Curl de Muñeca Palmas hacia Abajo sobre en Banco'),
  ('Palms-Up Barbell Wrist Curl Over A Bench', 'Curl de Muñeca Palmas hacia Arriba sobre en Banco con Barra'),
  ('Palms-Up Dumbbell Wrist Curl Over A Bench', 'Curl de Muñeca Palmas hacia Arriba sobre en Banco con Mancuerna'),
  ('Parallel Bar Dip', 'Fondo Parallel Barra'),
  ('Pelvic Tilt Into Bridge', 'Puente Pélvica Inclinación Into'),
  ('Peroneals Stretch', 'Estiramiento Peroneals'),
  ('Peroneals-SMR', 'Peroneals (SMR)'),
  ('Physioball Hip Bridge', 'Puente Physioball de Cadera'),
  ('Pin Presses', 'Press desde Pines'),
  ('Piriformis-SMR', 'Piriformis (SMR)'),
  ('Plank', 'Plancha'),
  ('Plate Pinch', 'Pinch con Disco'),
  ('Plate Twist', 'Giro con Disco'),
  ('Platform Hamstring Slides', 'Platform Slides Femoral'),
  ('Plie Dumbbell Squat', 'Sentadilla Plié con Mancuerna'),
  ('Plyo Kettlebell Pushups', 'Plyo Pushups con Pesa Rusa'),
  ('Plyo Push-up', 'Flexión Plyo'),
  ('Posterior Tibialis Stretch', 'Estiramiento Posterior Tibial'),
  ('Power Clean', 'Cargada de Potencia'),
  ('Power Clean from Blocks', 'Cargada de Potencia con Bloques'),
  ('Power Jerk', 'Envión de Potencia'),
  ('Power Partials', 'de Potencia Partials'),
  ('Power Snatch', 'Arranque de Potencia'),
  ('Power Snatch from Blocks', 'Arranque de Potencia con Bloques'),
  ('Power Stairs', 'Escaleras de Potencia'),
  ('Preacher Curl', 'Curl en Banco Scott'),
  ('Preacher Hammer Dumbbell Curl', 'Curl Martillo en Banco Scott con Mancuerna'),
  ('Press Sit-Up', 'Abdominal Press'),
  ('Prone Manual Hamstring', 'Manual Femoral Boca Abajo'),
  ('Prowler Sprint', 'Prowler Sprint'),
  ('Pull Through', 'Tirón entre Piernas'),
  ('Pullups', 'Dominadas'),
  ('Push Press', 'Push Press'),
  ('Push Press - Behind the Neck', 'Press de Empuje tras la Nuca'),
  ('Push Up to Side Plank', 'Flexión Plank Lateral'),
  ('Push-Up Wide', 'Flexión Abierto'),
  ('Push-Ups - Close Triceps Position', 'de Empuje Cerrado Position de Tríceps'),
  ('Push-Ups With Feet Elevated', 'de Empuje Feet Elevado'),
  ('Push-Ups With Feet On An Exercise Ball', 'de Empuje Feet con Pelota'),
  ('Pushups', 'Flexiones'),
  ('Pushups (Close and Wide Hand Positions)', 'Pushups Abierto (Close Hand Positions)'),
  ('Pyramid', 'Pirámide'),
  ('Quad Stretch', 'Estiramiento de Cuádriceps'),
  ('Quadriceps-SMR', 'Quadriceps (SMR)'),
  ('Quick Leap', 'Quick Leap'),
  ('Rack Delivery', 'Rack Delivery'),
  ('Rack Pull with Bands', 'Tirón Rack con Bandas'),
  ('Rack Pulls', 'Rack Pulls'),
  ('Rear Leg Raises', 'Elevaciones Posterior de Piernas'),
  ('Recumbent Bike', 'Bicicleta Reclinada'),
  ('Return Push from Stance', 'Return de Empuje de Postura'),
  ('Reverse Band Bench Press', 'Press de Banca Inverso con Banda'),
  ('Reverse Band Box Squat', 'Sentadilla Inverso en Cajón con Banda'),
  ('Reverse Band Deadlift', 'Peso Muerto Inverso con Banda'),
  ('Reverse Band Power Squat', 'Sentadilla Inverso de Potencia con Banda'),
  ('Reverse Band Sumo Deadlift', 'Peso Muerto Sumo Inverso con Banda'),
  ('Reverse Barbell Curl', 'Curl Inverso con Barra'),
  ('Reverse Barbell Preacher Curls', 'Curls en Banco Scott Inverso con Barra'),
  ('Reverse Cable Curl', 'Curl Inverso en Polea'),
  ('Reverse Crunch', 'Crunch Inverso'),
  ('Reverse Flyes', 'Aperturas Inverso'),
  ('Reverse Flyes With External Rotation', 'Rotación Inverso Flyes Externa'),
  ('Reverse Grip Bent-Over Rows', 'Remos Inclinado con Agarre Inverso'),
  ('Reverse Grip Triceps Pushdown', 'Extensión de Tríceps en Polea con Agarre Inverso'),
  ('Reverse Hyperextension', 'Hiperextensión Inverso'),
  ('Reverse Machine Flyes', 'Aperturas Inverso en Máquina'),
  ('Reverse Plate Curls', 'Curls Inverso con Disco'),
  ('Reverse Triceps Bench Press', 'Press de Banca Inverso de Tríceps'),
  ('Rhomboids-SMR', 'Rhomboids (SMR)'),
  ('Rickshaw Carry', 'Acarreo Rickshaw'),
  ('Rickshaw Deadlift', 'Peso Muerto Rickshaw'),
  ('Ring Dips', 'Fondos Ring'),
  ('Rocket Jump', 'Salto con Salto'),
  ('Rocking Standing Calf Raise', 'Elevación de Talones Balanceo de Pie'),
  ('Rocky Pull-Ups/Pulldowns', 'Rocky Pull Ups/Pulldowns'),
  ('Romanian Deadlift', 'Peso Muerto Rumano'),
  ('Romanian Deadlift from Deficit', 'Peso Muerto Rumano Deficit'),
  ('Rope Climb', 'Escalada de Cuerda'),
  ('Rope Crunch', 'Crunch con Cuerda'),
  ('Rope Jumping', 'Jumping con Cuerda'),
  ('Rope Straight-Arm Pulldown', 'Jalón con Brazos Rectos con Cuerda'),
  ('Round The World Shoulder Stretch', 'Estiramiento Round del Mundo de Hombros'),
  ('Rowing, Stationary', 'Remo Estático'),
  ('Runner''s Stretch', 'Estiramiento Runner''S'),
  ('Running, Treadmill', 'Carrera en Cinta'),
  ('Russian Twist', 'Giro Ruso'),
  ('Sandbag Load', 'Sandbag Load'),
  ('Scapular Pull-Up', 'Dominada Escapular'),
  ('Scissor Kick', 'Tijera Patada'),
  ('Scissors Jump', 'Salto de Tijera'),
  ('Seated Band Hamstring Curl', 'Curl Femoral Sentado con Banda'),
  ('Seated Barbell Military Press', 'Press Militar Sentado con Barra'),
  ('Seated Barbell Twist', 'Giro Sentado con Barra'),
  ('Seated Bent-Over One-Arm Dumbbell Triceps Extension', 'Extensión de Tríceps Inclinado Sentado con Mancuerna a Un Brazo'),
  ('Seated Bent-Over Rear Delt Raise', 'Elevación de Deltoides Posterior Inclinado Sentado'),
  ('Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'Extensión de Tríceps a Dos Brazos Inclinado Sentado con Mancuerna'),
  ('Seated Biceps', 'Estiramiento de Bíceps Sentado'),
  ('Seated Cable Rows', 'Remos Sentado en Polea'),
  ('Seated Cable Shoulder Press', 'Press de Hombros Sentado en Polea'),
  ('Seated Calf Raise', 'Elevación de Talones Sentado'),
  ('Seated Calf Stretch', 'Estiramiento de Pantorrillas Sentado'),
  ('Seated Close-Grip Concentration Barbell Curl', 'Curl Concentrado con Agarre Cerrado Sentado con Barra'),
  ('Seated Dumbbell Curl', 'Curl Sentado con Mancuerna'),
  ('Seated Dumbbell Inner Biceps Curl', 'Curl de Bíceps Inner Sentado con Mancuerna'),
  ('Seated Dumbbell Palms-Down Wrist Curl', 'Curl de Muñeca Palmas hacia Abajo Sentado con Mancuerna'),
  ('Seated Dumbbell Palms-Up Wrist Curl', 'Curl de Muñeca Palmas hacia Arriba Sentado con Mancuerna'),
  ('Seated Dumbbell Press', 'Press Sentado con Mancuerna'),
  ('Seated Flat Bench Leg Pull-In', 'en Banco Pull de Piernas Sentado Plano'),
  ('Seated Floor Hamstring Stretch', 'Estiramiento Femoral Sentado en el Suelo'),
  ('Seated Front Deltoid', 'de Deltoides Frontal Sentado'),
  ('Seated Glute', 'Estiramiento de Glúteos Sentado'),
  ('Seated Good Mornings', 'Good Mornings Sentado'),
  ('Seated Hamstring', 'Estiramiento Isquiotibial Sentado'),
  ('Seated Hamstring and Calf Stretch', 'Estiramiento de Pantorrilla Femoral Sentado'),
  ('Seated Head Harness Neck Resistance', 'de Cabeza Harness Resistance de Cuello Sentado'),
  ('Seated Leg Curl', 'Curl Femoral Sentado'),
  ('Seated Leg Tucks', 'Tucks de Piernas Sentado'),
  ('Seated One-arm Cable Pulley Rows', 'Remos en Polea Sentado en Polea a Un Brazo'),
  ('Seated One-Arm Dumbbell Palms-Down Wrist Curl', 'Curl de Muñeca Palmas hacia Abajo Sentado con Mancuerna a Un Brazo'),
  ('Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'Curl de Muñeca Palmas hacia Arriba Sentado con Mancuerna a Un Brazo'),
  ('Seated Overhead Stretch', 'Estiramiento Sentado sobre la Cabeza'),
  ('Seated Palm-Up Barbell Wrist Curl', 'Curl de Muñeca Palma hacia Arriba Sentado con Barra'),
  ('Seated Palms-Down Barbell Wrist Curl', 'Curl de Muñeca Palmas hacia Abajo Sentado con Barra'),
  ('Seated Side Lateral Raise', 'Elevación Lateral Lateral Sentado'),
  ('Seated Triceps Press', 'Press de Tríceps Sentado'),
  ('Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'Curl de Muñeca a Dos Brazos Palmas hacia Arriba en Polea Baja Sentado'),
  ('See-Saw Press (Alternating Side Press)', 'Press See Sierra Press (Alternating Lateral'),
  ('Shotgun Row', 'Remo Shotgun'),
  ('Shoulder Circles', 'Círculos de Hombros'),
  ('Shoulder Press - With Bands', 'Press de Hombros con Bandas'),
  ('Shoulder Raise', 'Elevación de Hombros'),
  ('Shoulder Stretch', 'Estiramiento de Hombros'),
  ('Side Bridge', 'Plancha Lateral'),
  ('Side Hop-Sprint', 'Hop Sprint Lateral'),
  ('Side Jackknife', 'Navaja Lateral'),
  ('Side Lateral Raise', 'Elevación Lateral Lateral'),
  ('Side Laterals to Front Raise', 'Elevación Frontal Laterals Lateral'),
  ('Side Leg Raises', 'Elevaciones Lateral de Piernas'),
  ('Side Lying Groin Stretch', 'Estiramiento de Ingle Lateral Acostado'),
  ('Side Neck Stretch', 'Estiramiento Lateral de Cuello'),
  ('Side Standing Long Jump', 'Salto Largo Lateral de Pie'),
  ('Side to Side Box Shuffle', 'Lateral en Cajón Shuffle Lateral'),
  ('Side To Side Chins', 'Lateral Chins Lateral'),
  ('Side Wrist Pull', 'Tirón Lateral de Muñeca'),
  ('Side-Lying Floor Stretch', 'Estiramiento Lateral Lying en el Suelo'),
  ('Single Dumbbell Raise', 'Elevación a Una con Mancuerna'),
  ('Single Leg Butt Kick', 'a Una Butt Patada de Piernas'),
  ('Single Leg Glute Bridge', 'Puente de Glúteos a Una de Piernas'),
  ('Single Leg Push-off', 'a Una de Empuje de Piernas'),
  ('Single-Arm Cable Crossover', 'Cruce en Polea a Un Brazo'),
  ('Single-Arm Linear Jammer', 'Lineal Jammer a Un Brazo'),
  ('Single-Arm Push-Up', 'Flexión a Un Brazo'),
  ('Single-Cone Sprint Drill', 'a Una Cone Sprint Drill'),
  ('Single-Leg High Box Squat', 'Sentadilla en Cajón Alto a Una Pierna'),
  ('Single-Leg Hop Progression', 'Hop Progression a Una Pierna'),
  ('Single-Leg Lateral Hop', 'Hop Lateral a Una Pierna'),
  ('Single-Leg Leg Extension', 'Extensión de Cuádriceps a Una Pierna'),
  ('Single-Leg Stride Jump', 'Salto a Una Pierna'),
  ('Sit Squats', 'Sentadillas en Silla'),
  ('Sit-Up', 'Abdominal'),
  ('Skating', 'Skating'),
  ('Sled Drag - Harness', 'Arrastre Harness con Trineo'),
  ('Sled Overhead Backward Walk', 'Caminata hacia Atrás sobre la Cabeza con Trineo'),
  ('Sled Overhead Triceps Extension', 'Extensión de Tríceps sobre la Cabeza con Trineo'),
  ('Sled Push', 'de Empuje con Trineo'),
  ('Sled Reverse Flye', 'Apertura Inverso con Trineo'),
  ('Sled Row', 'Remo con Trineo'),
  ('Sledgehammer Swings', 'Golpes con Mazo'),
  ('Smith Incline Shoulder Raise', 'Elevación en Máquina Smith de Hombros Inclinado'),
  ('Smith Machine Behind the Back Shrug', 'Encogimiento en Máquina Smith tras la Espalda'),
  ('Smith Machine Bench Press', 'Press de Banca en Máquina Smith'),
  ('Smith Machine Bent Over Row', 'Remo Inclinado en Máquina Smith'),
  ('Smith Machine Calf Raise', 'Elevación de Talones en Máquina Smith'),
  ('Smith Machine Close-Grip Bench Press', 'Press de Banca con Agarre Cerrado en Máquina Smith'),
  ('Smith Machine Decline Press', 'Press Declinado en Máquina Smith'),
  ('Smith Machine Hang Power Clean', 'Cargada Colgante de Potencia en Máquina Smith'),
  ('Smith Machine Hip Raise', 'Elevación de Cadera en Máquina Smith'),
  ('Smith Machine Incline Bench Press', 'Press de Banca Inclinado en Máquina Smith'),
  ('Smith Machine Leg Press', 'Prensa de Piernas en Máquina Smith'),
  ('Smith Machine One-Arm Upright Row', 'Remo al Mentón en Máquina Smith a Un Brazo'),
  ('Smith Machine Overhead Shoulder Press', 'Press de Hombros sobre la Cabeza en Máquina Smith'),
  ('Smith Machine Pistol Squat', 'Sentadilla Pistol en Máquina Smith'),
  ('Smith Machine Reverse Calf Raises', 'Elevaciones Inverso de Pantorrillas en Máquina Smith'),
  ('Smith Machine Squat', 'Sentadilla en Máquina Smith'),
  ('Smith Machine Stiff-Legged Deadlift', 'Peso Muerto Rígidas de Piernas en Máquina Smith'),
  ('Smith Machine Upright Row', 'Remo al Mentón en Máquina Smith'),
  ('Smith Single-Leg Split Squat', 'Sentadilla en Máquina Smith Dividida a Una Pierna'),
  ('Snatch', 'Arranque'),
  ('Snatch Balance', 'Arranque Balance'),
  ('Snatch Deadlift', 'Peso Muerto Arranque'),
  ('Snatch from Blocks', 'Arranque con Bloques'),
  ('Snatch Pull', 'Tirón Arranque'),
  ('Snatch Shrug', 'Encogimiento Arranque'),
  ('Speed Band Overhead Triceps', 'Speed de Tríceps sobre la Cabeza con Banda'),
  ('Speed Box Squat', 'Sentadilla Speed en Cajón'),
  ('Speed Squats', 'Sentadillas Speed'),
  ('Spell Caster', 'Deletreo (Spell-Caster) Caster'),
  ('Spider Crawl', 'Escalador Araña'),
  ('Spider Curl', 'Curl Araña'),
  ('Spinal Stretch', 'Estiramiento Spinal'),
  ('Split Clean', 'Cargada Dividida'),
  ('Split Jerk', 'Envión Dividida'),
  ('Split Jump', 'Salto Dividida'),
  ('Split Snatch', 'Arranque Dividida'),
  ('Split Squat with Dumbbells', 'Sentadilla Dividida con Mancuernas'),
  ('Split Squats', 'Sentadillas Dividida'),
  ('Squat Jerk', 'Sentadilla con Envión'),
  ('Squat with Bands', 'Sentadilla con Bandas'),
  ('Squat with Chains', 'Sentadilla con Cadenas'),
  ('Squat with Plate Movers', 'Sentadilla Movers con Disco'),
  ('Squats - With Bands', 'Sentadillas con Bandas'),
  ('Stairmaster', 'Escaladora'),
  ('Standing Alternating Dumbbell Press', 'Press de Pie con Mancuerna Alterno'),
  ('Standing Barbell Calf Raise', 'Elevación de Talones de Pie con Barra'),
  ('Standing Barbell Press Behind Neck', 'Press de Pie con Barra tras la Nuca'),
  ('Standing Bent-Over One-Arm Dumbbell Triceps Extension', 'Extensión de Tríceps Inclinado de Pie con Mancuerna a Un Brazo'),
  ('Standing Bent-Over Two-Arm Dumbbell Triceps Extension', 'Extensión de Tríceps a Dos Brazos Inclinado de Pie con Mancuerna'),
  ('Standing Biceps Cable Curl', 'Curl de Bíceps de Pie en Polea'),
  ('Standing Biceps Stretch', 'Estiramiento de Bíceps de Pie'),
  ('Standing Bradford Press', 'Press Bradford de Pie'),
  ('Standing Cable Chest Press', 'Press de Pecho de Pie en Polea'),
  ('Standing Cable Lift', 'Levantamiento de Pie en Polea'),
  ('Standing Cable Wood Chop', 'Wood Leñador de Pie en Polea'),
  ('Standing Calf Raises', 'Elevación de Talones de Pie'),
  ('Standing Concentration Curl', 'Curl Concentrado de Pie'),
  ('Standing Dumbbell Calf Raise', 'Elevación de Talones de Pie con Mancuerna'),
  ('Standing Dumbbell Press', 'Press de Pie con Mancuerna'),
  ('Standing Dumbbell Reverse Curl', 'Curl Inverso de Pie con Mancuerna'),
  ('Standing Dumbbell Straight-Arm Front Delt Raise Above Head', 'Elevación con Brazos Rectos de Deltoides Above de Cabeza Frontal de Pie con Mancuerna'),
  ('Standing Dumbbell Triceps Extension', 'Extensión de Tríceps de Pie con Mancuerna'),
  ('Standing Dumbbell Upright Row', 'Remo al Mentón de Pie con Mancuerna'),
  ('Standing Elevated Quad Stretch', 'Estiramiento Elevado de Cuádriceps de Pie'),
  ('Standing Front Barbell Raise Over Head', 'Elevación sobre de Cabeza Frontal de Pie con Barra'),
  ('Standing Gastrocnemius Calf Stretch', 'Estiramiento Gastrocnemius de Pantorrillas de Pie'),
  ('Standing Hamstring and Calf Stretch', 'Estiramiento de Pantorrilla Femoral de Pie'),
  ('Standing Hip Circles', 'Círculos de Cadera de Pie'),
  ('Standing Hip Flexors', 'de Cadera Flexors de Pie'),
  ('Standing Inner-Biceps Curl', 'Curl Inner Biceps de Pie'),
  ('Standing Lateral Stretch', 'Estiramiento Lateral de Pie'),
  ('Standing Leg Curl', 'Curl Femoral de Pie'),
  ('Standing Long Jump', 'Salto Largo de Pie'),
  ('Standing Low-Pulley Deltoid Raise', 'Elevación en Polea Baja de Deltoides de Pie'),
  ('Standing Low-Pulley One-Arm Triceps Extension', 'Extensión de Tríceps en Polea Baja de Pie a Un Brazo'),
  ('Standing Military Press', 'Press Militar de Pie'),
  ('Standing Olympic Plate Hand Squeeze', 'Olympic Hand Squeeze de Pie con Disco'),
  ('Standing One-Arm Cable Curl', 'Curl de Pie en Polea a Un Brazo'),
  ('Standing One-Arm Dumbbell Curl Over Incline Bench', 'Curl sobre en Banco Inclinado de Pie con Mancuerna a Un Brazo'),
  ('Standing One-Arm Dumbbell Triceps Extension', 'Extensión de Tríceps de Pie con Mancuerna a Un Brazo'),
  ('Standing Overhead Barbell Triceps Extension', 'Extensión de Tríceps de Pie sobre la Cabeza con Barra'),
  ('Standing Palm-In One-Arm Dumbbell Press', 'Press Palma de Pie con Mancuerna a Un Brazo'),
  ('Standing Palms-In Dumbbell Press', 'Press Palmas de Pie con Mancuerna'),
  ('Standing Palms-Up Barbell Behind The Back Wrist Curl', 'Curl de Muñeca Palmas hacia Arriba de Pie con Barra tras la Espalda'),
  ('Standing Pelvic Tilt', 'Pélvica Inclinación de Pie'),
  ('Standing Rope Crunch', 'Crunch de Pie con Cuerda'),
  ('Standing Soleus And Achilles Stretch', 'Estiramiento Soleus Achilles de Pie'),
  ('Standing Toe Touches', 'Toques de Punta de Pie'),
  ('Standing Towel Triceps Extension', 'Extensión de Tríceps Towel de Pie'),
  ('Standing Two-Arm Overhead Throw', 'Lanzamiento a Dos Brazos de Pie sobre la Cabeza'),
  ('Star Jump', 'Salto Estrella'),
  ('Step Mill', 'de Paso Mill'),
  ('Step-up with Knee Raise', 'Subida al Cajón de Rodilla Raise'),
  ('Stiff Leg Barbell Good Morning', 'Buenos Días Rígidas de Piernas con Barra'),
  ('Stiff-Legged Barbell Deadlift', 'Peso Muerto Rígidas de Piernas con Barra'),
  ('Stiff-Legged Dumbbell Deadlift', 'Peso Muerto Rígidas de Piernas con Mancuerna'),
  ('Stomach Vacuum', 'Stomach Vacuum'),
  ('Straight Bar Bench Mid Rows', 'Remos Recta Barra en Banco Mid'),
  ('Straight Raises on Incline Bench', 'Elevaciones Recta en Banco Inclinado'),
  ('Straight-Arm Dumbbell Pullover', 'Pull-over con Brazos Rectos con Mancuerna'),
  ('Straight-Arm Pulldown', 'Jalón con Brazos Rectos'),
  ('Stride Jump Crossover', 'Salto Stride Cruce'),
  ('Sumo Deadlift', 'Peso Muerto Sumo'),
  ('Sumo Deadlift with Bands', 'Peso Muerto Sumo con Bandas'),
  ('Sumo Deadlift with Chains', 'Peso Muerto Sumo con Cadenas'),
  ('Superman', 'Superman'),
  ('Supine Chest Throw', 'Lanzamiento de Pecho Boca Arriba'),
  ('Supine One-Arm Overhead Throw', 'Lanzamiento sobre la Cabeza Boca Arriba a Un Brazo'),
  ('Supine Two-Arm Overhead Throw', 'Lanzamiento a Dos Brazos sobre la Cabeza Boca Arriba'),
  ('Suspended Fallout', 'en Suspensión Fallout'),
  ('Suspended Push-Up', 'Flexión en Suspensión'),
  ('Suspended Reverse Crunch', 'Crunch Inverso en Suspensión'),
  ('Suspended Row', 'Remo en Suspensión'),
  ('Suspended Split Squat', 'Sentadilla en Suspensión Dividida'),
  ('Svend Press', 'Press Svend'),
  ('T-Bar Row with Handle', 'Remo T Barra Handle'),
  ('Tate Press', 'Press Tate'),
  ('The Straddle', 'Straddle'),
  ('Thigh Abductor', 'Thigh Abductor'),
  ('Thigh Adductor', 'Thigh Adductor'),
  ('Tire Flip', 'Volteo de Neumático'),
  ('Toe Touchers', 'Toques de Punta'),
  ('Torso Rotation', 'Rotación Torso'),
  ('Trail Running/Walking', 'Carrera/Caminata en Sendero'),
  ('Trap Bar Deadlift', 'Peso Muerto de Trapecio Barra'),
  ('Tricep Dumbbell Kickback', 'Patada de Tríceps con Mancuerna'),
  ('Tricep Side Stretch', 'Estiramiento Lateral de Tríceps'),
  ('Triceps Overhead Extension with Rope', 'Extensión de Tríceps sobre la Cabeza con Cuerda'),
  ('Triceps Pushdown', 'Extensión de Tríceps en Polea'),
  ('Triceps Pushdown - Rope Attachment', 'Extensión de Tríceps en Polea con Accesorio con Cuerda'),
  ('Triceps Pushdown - V-Bar Attachment', 'Extensión de Tríceps en Polea con Barra V con Accesorio'),
  ('Triceps Stretch', 'Estiramiento de Tríceps'),
  ('Tuck Crunch', 'Crunch Encogido'),
  ('Two-Arm Dumbbell Preacher Curl', 'Curl en Banco Scott a Dos Brazos con Mancuerna'),
  ('Two-Arm Kettlebell Clean', 'Cargada a Dos Brazos con Pesa Rusa'),
  ('Two-Arm Kettlebell Jerk', 'Envión a Dos Brazos con Pesa Rusa'),
  ('Two-Arm Kettlebell Military Press', 'Press Militar a Dos Brazos con Pesa Rusa'),
  ('Two-Arm Kettlebell Row', 'Remo a Dos Brazos con Pesa Rusa'),
  ('Underhand Cable Pulldowns', 'Underhand Pulldowns en Polea'),
  ('Upper Back Stretch', 'Estiramiento Superior de Espalda'),
  ('Upper Back-Leg Grab', 'Superior de Espalda Leg Grab'),
  ('Upright Barbell Row', 'Remo Upright con Barra'),
  ('Upright Cable Row', 'Remo Upright en Polea'),
  ('Upright Row - With Bands', 'Remo al Mentón con Bandas'),
  ('Upward Stretch', 'Estiramiento hacia Arriba'),
  ('V-Bar Pulldown', 'Jalón con Barra V'),
  ('V-Bar Pullup', 'con Barra V Pullup'),
  ('Vertical Swing', 'Balanceo Vertical'),
  ('Walking, Treadmill', 'Caminata en Cinta'),
  ('Weighted Ball Hyperextension', 'con Pelota Hiperextensión con Peso'),
  ('Weighted Ball Side Bend', 'con Pelota Flexión Lateral con Peso'),
  ('Weighted Bench Dip', 'Fondo en Banco con Peso'),
  ('Weighted Crunches', 'Crunches con Peso'),
  ('Weighted Jump Squat', 'Sentadilla con Salto con Peso'),
  ('Weighted Pull Ups', 'Tirón con Peso'),
  ('Weighted Sissy Squat', 'Sentadilla Sissy con Peso'),
  ('Weighted Sit-Ups - With Bands', 'Sit con Peso con Bandas'),
  ('Weighted Squat', 'Sentadilla con Peso'),
  ('Wide Stance Barbell Squat', 'Sentadilla Abierto de Postura con Barra'),
  ('Wide Stance Stiff Legs', 'de Postura Abierto Rígidas de Piernas'),
  ('Wide-Grip Barbell Bench Press', 'Press de Banca con Agarre Abierto con Barra'),
  ('Wide-Grip Decline Barbell Bench Press', 'Press de Banca con Agarre Abierto Declinado con Barra'),
  ('Wide-Grip Decline Barbell Pullover', 'Pull-over con Agarre Abierto Declinado con Barra'),
  ('Wide-Grip Lat Pulldown', 'Jalón al Pecho con Agarre Abierto'),
  ('Wide-Grip Pulldown Behind The Neck', 'Jalón con Agarre Abierto tras la Nuca'),
  ('Wide-Grip Rear Pull-Up', 'Dominada con Agarre Abierto Posterior'),
  ('Wide-Grip Standing Barbell Curl', 'Curl con Agarre Abierto de Pie con Barra'),
  ('Wind Sprints', 'Sprints'),
  ('Windmills', 'Molinos'),
  ('World''s Greatest Stretch', 'El Mejor Estiramiento del Mundo'),
  ('Wrist Circles', 'Círculos de Muñeca'),
  ('Wrist Roller', 'Rodillo de Muñeca'),
  ('Wrist Rotations with Straight Bar', 'Rotaciones de Muñeca con Barra Recta'),
  ('Yoke Walk', 'Caminata con Yugo'),
  ('Zercher Squats', 'Sentadillas Zercher'),
  ('Zottman Curl', 'Curl Zottman'),
  ('Zottman Preacher Curl', 'Curl Zottman en Banco Scott')
) as v(name_en, es) where e.name_en = v.name_en;
