-- 0048 PHASE 2 -- Bilingual recipe names. Stephanie's 158 imported recipes had name_es = null. Hand-
-- translated to LATAM Spanish (Mexican-leaning vocabulary: camarones, ejotes, aguacate, camote,
-- mantequilla de maní), keeping brand names (Biscoff, Nutella, Fairlife, Halo Top) and proper dish
-- names (Shakshuka, Fattoush, Tandoori, Banh mi). Idempotent (name_en-keyed). procedure_es (the full
-- cooking steps) is a separate, larger pass and stays null for now.

update public.recipes r set name_es = v.es from (values
  ('Apple chocolate lollipops with cottage cheese and milk', 'Paletas de manzana y chocolate con requesón y leche'),
  ('Asian lettuce wrap with turkey slices', 'Wrap asiático de lechuga con lonchas de pavo'),
  ('Asian shrimp salad with rice noodles', 'Ensalada asiática de camarones con fideos de arroz'),
  ('Asian style cabbage and bean sprout salad with chicken', 'Ensalada estilo asiático de col y germinado de soja con pollo'),
  ('Avocado toast with cottage cheese and pomegranate seeds ❤️', 'Tostada de aguacate con requesón y semillas de granada ❤️'),
  ('Bacon Egg & Cheese Breakfast Bagels', 'Bagels de desayuno con tocino, huevo y queso'),
  ('Baked lentil falafel with tzatziki', 'Falafel de lentejas al horno con tzatziki'),
  ('Baked vegetables and salmon with lemon', 'Verduras y salmón al horno con limón'),
  ('Banana and almond butter smoothie', 'Batido de plátano y mantequilla de almendras'),
  ('Banana and Biscoff overnight oats', 'Avena nocturna de plátano y Biscoff'),
  ('Banana and Nutella French toast', 'Tostada francesa de plátano y Nutella'),
  ('Banana muffins with chocolate chunks', 'Muffins de plátano con trozos de chocolate'),
  ('Banana pancakes with Greek yogurt, blueberries, and syrup', 'Panqueques de plátano con yogur griego, arándanos y sirope'),
  ('Banana protein pancakes with maple syrup', 'Panqueques proteicos de plátano con sirope de arce'),
  ('Banana, coconut oil and skyr protein smoothie', 'Batido proteico de plátano, aceite de coco y skyr'),
  ('Barebell protein', 'Proteína Barebell'),
  ('Barebell protein bar', 'Barra de proteína Barebell'),
  ('Birria Tacos', 'Tacos de birria'),
  ('Biscoff French toast', 'Tostada francesa de Biscoff'),
  ('Black bean enchiladas with chicken', 'Enchiladas de frijol negro con pollo'),
  ('Blueberry and peanut butter smoothie', 'Batido de arándanos y mantequilla de maní'),
  ('Breakfast tacos with eggs, tomatoes and cottage cheese', 'Tacos de desayuno con huevo, tomate y requesón'),
  ('Broccoli and zucchini stir fry', 'Salteado de brócoli y calabacín'),
  ('Bulgur salad with boiled chicken and pomegranate', 'Ensalada de bulgur con pollo hervido y granada'),
  ('Butter chicken', 'Pollo a la mantequilla (Butter Chicken)'),
  ('Caesar salad', 'Ensalada César'),
  ('Cajun style chicken with rice', 'Pollo estilo cajún con arroz'),
  ('Carrot muffins', 'Muffins de zanahoria'),
  ('Chia overnight oats', 'Avena nocturna con chía'),
  ('Chia power smoothie', 'Batido energético de chía'),
  ('Chicken and bacon burger', 'Hamburguesa de pollo y tocino'),
  ('Chicken and banana curry', 'Curry de pollo y plátano'),
  ('Chicken and vegetable curry with rice', 'Curry de pollo y verduras con arroz'),
  ('Chicken Caesar Lettuce Wraps', 'Wraps de lechuga con pollo César'),
  ('Chicken carbonara with mushrooms', 'Pollo a la carbonara con champiñones'),
  ('Chicken teriyaki with broccoli', 'Pollo teriyaki con brócoli'),
  ('Chickpea and spinach shakshuka', 'Shakshuka de garbanzos y espinacas'),
  ('Chili sin carne with chickpeas', 'Chili sin carne con garbanzos'),
  ('Chili tomato and shrimp pasta', 'Pasta de camarones con tomate y chile'),
  ('Chocolate and hazelnut yogurt bowl', 'Bol de yogur con chocolate y avellana'),
  ('Chocolate hazelnut raw date balls', 'Bolitas crudas de dátil, chocolate y avellana'),
  ('Chocolate muffins', 'Muffins de chocolate'),
  ('Chunky Monkey Yogurt Bowl', 'Bol de yogur Chunky Monkey'),
  ('Classic pasta Bolognese', 'Pasta boloñesa clásica'),
  ('Cocoa and peanut butter muffins', 'Muffins de cacao y mantequilla de maní'),
  ('Coconut curry soup with chicken', 'Sopa de curry y coco con pollo'),
  ('Coconut rice with tilapia', 'Arroz con coco y tilapia'),
  ('Coconut shrimp', 'Camarones al coco'),
  ('Cottage cheese pasta with parmesan', 'Pasta con requesón y parmesano'),
  ('Crispy chicken with soy sauce', 'Pollo crujiente con salsa de soja'),
  ('Curry and chili fried rice with chicken', 'Arroz frito con curry, chile y pollo'),
  ('Easy homemade falafel', 'Falafel casero fácil'),
  ('Edamame salad with tomatoes and cucumber', 'Ensalada de edamame con tomate y pepino'),
  ('Egg fried rice with green beans', 'Arroz frito con huevo y ejotes'),
  ('Egg muffins with spinach and ham', 'Muffins de huevo con espinaca y jamón'),
  ('Egg noodles with chicken and stir-fried vegetables', 'Fideos de huevo con pollo y verduras salteadas'),
  ('English muffin with egg and ham', 'Muffin inglés con huevo y jamón'),
  ('Fairlife Chocolate Protein Shake', 'Batido de proteína Fairlife de chocolate'),
  ('Fast homemade raspberry ice cream', 'Helado casero rápido de frambuesa'),
  ('Fattoush (Lebanese pita and vegetable salad)', 'Fattoush (ensalada libanesa de pita y verduras)'),
  ('Fiber One Chocolate Fudge Brownie', 'Brownie de chocolate Fiber One'),
  ('Foul Mudammas - Egyptian Breakfast 🌱', 'Ful medames - desayuno egipcio 🌱'),
  ('Fruit salad ', 'Ensalada de frutas'),
  ('Fruit smoothie', 'Batido de frutas'),
  ('Ginger and chili Asian bowl with spicy tofu 🌱', 'Bol asiático de jengibre y chile con tofu picante 🌱'),
  ('Greek Pasta Salad', 'Ensalada griega de pasta'),
  ('Ground beef and rice with broccoli and carrots', 'Carne molida y arroz con brócoli y zanahoria'),
  ('Ground beef, green beans and rice with avocado', 'Carne molida, ejotes y arroz con aguacate'),
  ('Halo Top peanut butter ice cream ', 'Helado de mantequilla de maní Halo Top'),
  ('Halo Top peanut butter ice cream with waffle cone', 'Helado de mantequilla de maní Halo Top con cono de barquillo'),
  ('Harissa chicken', 'Pollo con harissa'),
  ('Hashbrowns with eggs and bacon', 'Papas ralladas con huevo y tocino'),
  ('Healthy cookies with oats and dried cranberries', 'Galletas saludables de avena y arándanos secos'),
  ('Homemade caramel popcorn', 'Palomitas de caramelo caseras'),
  ('Honey garlic wings with dill yogurt dip', 'Alitas con miel y ajo y salsa de yogur con eneldo'),
  ('Honeydew peach smoothie bowl with puffed quinoa', 'Bol de batido de melón y durazno con quinoa inflada'),
  ('In-n-Out Animal Style Fries Dupe', 'Imitación de papas Animal Style de In-n-Out'),
  ('Jamaican soursop smoothie', 'Batido jamaicano de guanábana'),
  ('Jimmy Dean breakfast sandwich', 'Sándwich de desayuno Jimmy Dean'),
  ('Lemon and chili tilapia with patatas bravas', 'Tilapia con limón y chile y patatas bravas'),
  ('Lemon and parsley cauliflower tabbouleh with pan-fried halloumi', 'Tabulé de coliflor con limón y perejil y halloumi a la sartén'),
  ('Low carb shrimp and grits with kale', 'Camarones bajos en carbohidratos con sémola de maíz y col rizada'),
  ('Magic spoon protein cereal ', 'Cereal proteico Magic Spoon'),
  ('Manakish with homemade labneh', 'Manakish con labneh casero'),
  ('Matcha breakfast bowl', 'Bol de desayuno de matcha'),
  ('McDonalds Apple Pie Dupe', 'Imitación de pay de manzana de McDonald''s'),
  ('Mediterranean quinoa salad with feta', 'Ensalada mediterránea de quinoa con feta'),
  ('Meva moodie (Bengali puffed rice and nut snack)', 'Meva moodie (snack bengalí de arroz inflado y nueces)'),
  ('Mini raspberry cheesecake', 'Mini cheesecake de frambuesa'),
  ('Mocha overnight oats', 'Avena nocturna de moca'),
  ('Oat protein shake with dark chocolate', 'Batido proteico de avena con chocolate negro'),
  ('Oreo overnight oats', 'Avena nocturna de Oreo'),
  ('Pan fried shrimp with rice and bell pepper', 'Camarones a la sartén con arroz y pimiento'),
  ('Pan-fried chicken with brown rice', 'Pollo a la sartén con arroz integral'),
  ('Papaya and banana smoothie', 'Batido de papaya y plátano'),
  ('Pasta salad with chicken and veggies', 'Ensalada de pasta con pollo y verduras'),
  ('Pasta with meat sauce', 'Pasta con salsa de carne'),
  ('Pasta with pan-fried chicken', 'Pasta con pollo a la sartén'),
  ('Pasta with shrimp and avocado', 'Pasta con camarones y aguacate'),
  ('Peanut butter cookies', 'Galletas de mantequilla de maní'),
  ('Peppermint French toast', 'Tostada francesa de menta'),
  ('Pilau chickpeas with pita bread', 'Garbanzos pilaf con pan pita'),
  ('Pork banh mi', 'Banh mi de cerdo'),
  ('Premier protein shake', 'Batido de proteína Premier'),
  ('Protein cereal & toast with cream cheese', 'Cereal proteico y tostada con queso crema'),
  ('Protein pancakes with blueberries', 'Panqueques proteicos con arándanos'),
  ('Protein polenta bowl with pear', 'Bol de polenta proteica con pera'),
  ('Protein shake ', 'Batido de proteína'),
  ('Protein smoothie with banana and coconut', 'Batido proteico con plátano y coco'),
  ('Protein smoothie with strawberries and banana', 'Batido proteico con fresas y plátano'),
  ('Quinoa taboulé with pan-fried chicken breast fillet', 'Tabulé de quinoa con filete de pechuga de pollo a la sartén'),
  ('Raspberry, coconut and banana smoothie with protein powder', 'Batido de frambuesa, coco y plátano con proteína en polvo'),
  ('Roasted sweet potato and broccoli with zesty lemon tuna salad', 'Camote y brócoli asados con ensalada de atún al limón'),
  ('RX bar', 'Barra RX'),
  ('Scrambled eggs, turkey bacon, toast and raspberries', 'Huevos revueltos, tocino de pavo, tostada y frambuesas'),
  ('Shrimp and pea fried rice with egg', 'Arroz frito con camarones, chícharos y huevo'),
  ('Shrimp and pesto spaghetti', 'Espagueti con camarones y pesto'),
  ('Simple chicken salad with croutons', 'Ensalada sencilla de pollo con crutones'),
  ('Simple chicken with potato and green beans', 'Pollo sencillo con papa y ejotes'),
  ('Simple chicken with rice and broccoli', 'Pollo sencillo con arroz y brócoli'),
  ('Simple jerk chicken with rice and mixed vegetables', 'Pollo jerk sencillo con arroz y verduras mixtas'),
  ('Simple oatmeal with blueberries and almonds', 'Avena sencilla con arándanos y almendras'),
  ('Simple peanut butter frappe', 'Frappé sencillo de mantequilla de maní'),
  ('Simple steak with rice and broccoli', 'Bistec sencillo con arroz y brócoli'),
  ('Smoky spice rub and honey lime glazed chicken thighs', 'Muslos de pollo con adobo ahumado y glaseado de miel y limón'),
  ('Smoky tilapia tacos with mango salsa', 'Tacos de tilapia ahumada con salsa de mango'),
  ('Smoothie bowl with strawberry, banana, and cashews', 'Bol de batido con fresa, plátano y anacardos'),
  ('Smoothie with strawberries, banana and peanut butter', 'Batido con fresas, plátano y mantequilla de maní'),
  ('Smore crackers', 'Galletas s''more'),
  ('Spiced cod fillet with rice and naan bread', 'Filete de bacalao especiado con arroz y pan naan'),
  ('Spicy beef with rice and broccoli', 'Carne de res picante con arroz y brócoli'),
  ('Spicy lime and turkey lettuce wraps', 'Wraps de lechuga con pavo y limón picante'),
  ('Spinach and edamame salad with crispy spiced chickpeas 🌱', 'Ensalada de espinaca y edamame con garbanzos especiados crujientes 🌱'),
  ('Spinach salad with sauteed shrimp and sweet potatoes 🛡️', 'Ensalada de espinaca con camarones salteados y camote 🛡️'),
  ('Steph''s Ground Beef Protein Pasta', 'Pasta proteica de carne molida de Steph'),
  ('Stir fried vegetables with coconut milk 🌱', 'Verduras salteadas con leche de coco 🌱'),
  ('Strawberry and blueberry smoothie with milk', 'Batido de fresa y arándano con leche'),
  ('Strawberry milkshake with chocolate', 'Malteada de fresa con chocolate'),
  ('Strawberry smoothie', 'Batido de fresa'),
  ('Summer roll salad with shrimp', 'Ensalada de rollito de verano con camarones'),
  ('Taco bowl with beef', 'Bol de tacos con carne de res'),
  ('Tandoori salmon with rice and cucumber salad', 'Salmón tandoori con arroz y ensalada de pepino'),
  ('Tandoori stew with chicken', 'Estofado tandoori con pollo'),
  ('Tex-Mex inspired turkey meatloaf', 'Pastel de carne de pavo estilo Tex-Mex'),
  ('Tilapia and rice', 'Tilapia con arroz'),
  ('Toast with scrambled eggs', 'Tostada con huevos revueltos'),
  ('Tortilla wrap with pan fried chicken and tomato salsa', 'Wrap de tortilla con pollo a la sartén y salsa de tomate'),
  ('Tuna with rice, avocado and cucumber', 'Atún con arroz, aguacate y pepino'),
  ('Turkey Stroganoff', 'Stroganoff de pavo'),
  ('Vanilla Glazed Donut', 'Dona glaseada de vainilla'),
  ('Vegan Mediterranean wraps', 'Wraps mediterráneos veganos'),
  ('Vegan Pasta ', 'Pasta vegana'),
  ('Yogurt chicken korma with rice', 'Korma de pollo con yogur y arroz'),
  ('Yogurt with passion fruit, raspberries, almonds, and coconut', 'Yogur con maracuyá, frambuesas, almendras y coco')
) as v(name_en, es) where r.name_en = v.name_en;
